[package]
name = "allsorts-tools"
version = "0.1.0"
authors = ["Wesley Moore <wes@wezm.net>"]
edition = "2018"

[[bin]]
name = "allsorts"
path = "src/main.rs"

[dependencies]
allsorts = { path = "../prince/src/fonts/allsorts" }
atty = "0.2"
encoding_rs = "0.8.16"
getopts = "0.2"
gumdrop = "0.7.0"
itertools = "0.8"
